Fix write-only image tests in kernel_image_methods (#330)
KhronosGroup/OpenCL-CTS pull request #1014
Opened 2020-10-13 13:50 UTC by james-morrissey-arm

Pass the right flags to the tests that create images to ensure valid
usage.

Fixes issue #330

Signed-off-by: James Morrissey <james.morrissey@arm.com>

2020-11-17 20:15 UTC, jrprice requested changes

2020-11-17 20:15 UTC, jrprice commented on test_conformance/images/kernel_image_methods/test_2D.cpp
> +        "#pragma OPENCL EXTENSION cl_khr_3d_image_writes : enable";
Adding this unconditionally may cause a problems for devices that don't support 3D image writes (e.g. 1.2 and 3.0 devices that don't support this extension). This should only be added when testing 3D images with `CL_MEM_WRITE_ONLY`, and that test should be skipped (somewhere earlier) if the device doesn't support this functionality.

2020-11-20 14:09 UTC, kpet commented
This now needs rebasing.

2020-11-20 15:56 UTC, jrprice approved these changes

2020-11-21 08:32 UTC, kpet approved these changes

2020-11-21 08:33 UTC, merged