Using helper functions for clCreateKernel
KhronosGroup/OpenCL-CTS pull request #1064
Opened 2020-11-20 14:01 UTC by ellnor01

Uses of clCreateKernel following create program helper
functions, have been incorporated into
create_single_kernel_helper when suitable.

Contributes #31

Signed-off-by: Ellen Norris-Thompson <ellen.norris-thompson@arm.com>

2020-11-20 16:14 UTC, jrprice approved these changes
LGTM, just suggest that we switch to the managed `*Wrapper` classes at the same time as changing code like this.

Appveyor Windows build is failing.

2020-11-20 16:14 UTC, jrprice commented on test_conformance/math_brute_force/main.cpp
> +    cl_kernel k;
Prefer `clKernelWrapper`.

Could also switch the to program to `clProgramWrapper`, but that's getting further from the scope of this PR so fine to leave that for later.

2020-11-20 16:14 UTC, jrprice commented on test_conformance/math_brute_force/main.cpp
> +    cl_kernel k;
`clKernelWrapper`

2020-11-20 16:14 UTC, jrprice commented on test_conformance/math_brute_force/main.cpp
> +    cl_kernel k;
`clKernelWrapper`

2020-12-02 10:47 UTC, kpet commented
@ellnor01 Could you take a look at the Windows CI and possibly use wrappers where suggested?

2020-12-23 22:42 UTC, jrprice submitted a review, later dismissed

2021-01-04 14:59 UTC, kpet requested changes

2021-01-04 14:59 UTC, kpet commented on test_common/harness/imageHelpers.cpp
> +            clReleaseKernel(kernel);
`kernel` is now a wrapper. You should remove the calls to `clReleaseKernel` altogether. There are a few more occurrences below.

2021-01-07 10:35 UTC, kpet approved these changes
LGTM

2021-01-07 11:34 UTC, merged