Reduce number of compilations in buffer suite
KhronosGroup/OpenCL-CTS pull request #1082
Opened 2020-12-11 13:54 UTC by ellnor01

Extracts program and kernel compilation from mem_flags loop
as they were being recompiled unnecessarily.

Fixes #1020

Signed-off-by: Ellen Norris-Thompson <ellen.norris-thompson@arm.com>

2020-12-11 15:38 UTC, jrprice requested changes
This is a great improvement, thanks!

I think there's a few misplaced frees, and I made one specific suggestion to help simplify things. We could really do with a managed wrapper class for aligned allocations to handle this automatically for `align_malloc`/`align_free` (could probably be done with `std::unique_ptr` and a custom deleter). This is beyond the scope of this PR though. Likewise, the `MTdataHolder` wrapper could be used as well to get rid of those manual deallocations in error conditions. Again, not needed in this PR, but worth considering as an further cleanup in the future.

2020-12-11 15:38 UTC, jrprice commented on test_conformance/buffers/test_buffer_fill.cpp
> +            align_free((void *)hostptr);
I don't think these frees should be here, since the lifetime of those allocations is within the inner loop.

2020-12-11 15:38 UTC, jrprice commented on test_conformance/buffers/test_buffer_fill.cpp
> +            pattern = (TestStruct *)malloc(ptrSize);
I suggest that we change this to be a non-pointer within the scope of this loop body, which would avoid all of the `free(pattern)` calls in all of the error cases. e.g.
```
TestStruct pattern;
pattern.a = ...;
...
clEnqueueFillBuffer(..., &pattern, ....)
```

2020-12-11 15:38 UTC, jrprice commented on test_conformance/buffers/test_buffer_map.cpp
> +            align_free(outptr[i]);
As above, I don't think this free should be here.

2020-12-11 15:38 UTC, jrprice commented on test_conformance/buffers/test_buffer_read.cpp
> +            align_free(inptr[i]);
As above, I don't think these frees should be there.

2020-12-11 15:38 UTC, jrprice commented on test_conformance/buffers/test_buffer_read.cpp
> +            align_free(inptr[i]);
As above, remove frees.

2020-12-11 15:38 UTC, jrprice commented on test_conformance/buffers/test_buffer_read.cpp
> +            align_free(inptr[i]);
As above, remove frees.

2020-12-11 15:38 UTC, jrprice commented on test_conformance/buffers/test_buffer_write.cpp
> +            align_free(outptr[i]);
Remove free.

2020-12-11 15:38 UTC, jrprice commented on test_conformance/buffers/test_buffer_write.cpp
> +            align_free(outptr[i]);
Remove free.

2020-12-17 18:46 UTC, jrprice approved these changes
LGTM, thanks!

2020-12-18 07:50 UTC, kpet approved these changes

2020-12-18 07:50 UTC, merged