Use memcmp for select verification.
KhronosGroup/OpenCL-CTS pull request #1084
Opened 2020-12-11 18:40 UTC by Jeremy-Kemp

If `memcmp` fails, fall back to looping through the result buffer to find the incorrect result.

Improves wimpy runtime by ~26% on my test device.

Starts to address points made in #1054

2020-12-11 19:01 UTC, jrprice requested changes
Good improvement, two minor comments.

2020-12-11 19:06 UTC, Jeremy-Kemp commented on test_conformance/select/util_select.cpp
> +    if (memcmp(t, c, count) != 0)
Good spot, thanks. I shouldn't have started with char ;)

2020-12-11 19:06 UTC, Jeremy-Kemp commented on test_conformance/select/util_select.cpp
> +                          vector_size, i + 3, count, c[i + 3], t[i + 3]);
I couldn't think of a reason that this one was special cased. I'll remove it if there are no objections.

2020-12-14 15:02 UTC, jrprice approved these changes
LGTM.

2020-12-16 10:38 UTC, EwanC approved these changes

2020-12-23 22:05 UTC, merged