Test cl_ext_cxx_for_opencl (#1075)
KhronosGroup/OpenCL-CTS pull request #1095
Opened 2021-01-05 12:18 UTC by AnastasiaStulova

Add tests for API extension for compilation
of kernels in C++ for OpenCL language.
* Test that -cl-std=CLC++ is accepted and a
  basic kernel with C++ features is compiled.
* Test that API extension reports the same
  language version as __OPENCL_CPP_VERSION__.

This commit also adds a separate folder for extension
tests.

2021-01-05 12:19 UTC, AnastasiaStulova commented on test_conformance/extensions/cl_ext_cxx_for_opencl/cxx_for_opencl_ext.cpp
> +// Copyright (c) 2020 The Khronos Group Inc.
The copyright year needs to change!

2021-01-05 12:20 UTC, AnastasiaStulova commented on test_conformance/extensions/cl_ext_cxx_for_opencl/cxx_for_opencl_ext.cpp
> +    in_buffer = clCreateBuffer(context, CL_MEM_READ_WRITE | CL_MEM_COPY_HOST_PTR, sizeof(value), &value,
The formating is different to the line 45 btw.

@kpet do we run clang-format or something?

2021-01-05 16:23 UTC, kpet requested changes
It would be nice to credit the original author of those tests. I suggest adding a Signed-off-by and maybe resetting the commit author as well so they're credited in the git history too.

2021-01-05 16:23 UTC, kpet commented on test_conformance/extensions/cl_ext_cxx_for_opencl/cxx_for_opencl_ext.cpp
> +                        bool useCoreSubgroups)
Some of the parameters are not necessary (at least `num_elements` and `useCoreSubgroups`).

2021-01-05 18:56 UTC, AnastasiaStulova commented
> It would be nice to credit the original author of those tests. I suggest adding a Signed-off-by and maybe resetting the commit author as well so they're credited in the git history too.

Ok I have updated the first (i.e. base) commit.

2021-01-06 11:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/OpenCL-CTS?pullRequest=1095) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/OpenCL-CTS?pullRequest=1095) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/OpenCL-CTS?pullRequest=1095) it.</sub>

2021-01-06 12:00 UTC, AnastasiaStulova commented
> > It would be nice to credit the original author of those tests. I suggest adding a Signed-off-by and maybe resetting the commit author as well so they're credited in the git history too.
> 
> Ok I have updated the first (i.e. base) commit.

This didn't work, so I have repushed it now. But there is an issue with CLA now because I think @VictoriaHolodovsky needs to sign it too?

2021-01-11 14:44 UTC, AnastasiaStulova commented
> > > It would be nice to credit the original author of those tests. I suggest adding a Signed-off-by and maybe resetting the commit author as well so they're credited in the git history too.
> > 
> > 
> > Ok I have updated the first (i.e. base) commit.
> 
> This didn't work, so I have repushed it now. But there is an issue with CLA now because I think @VictoriaHolodovsky needs to sign it too?

the CLA has been signed!

2021-01-12 09:24 UTC, kpet approved these changes

2021-01-12 09:50 UTC, gwawiork approved these changes
LGTM

2021-01-12 10:17 UTC, merged