Update cl_khr_integer_dot_product tests for v2
KhronosGroup/OpenCL-CTS pull request #1317
Opened 2021-09-03 12:51 UTC by kpet

Signed-off-by: Kevin Petit <kevin.petit@arm.com>
Signed-off-by: Marco Cattani <marco.cattani@arm.com>

2021-09-03 19:00 UTC, bashbaug requested changes
Mostly LGTM but I think the checks for acceleration properties need to be guarded by the check for version v2.  Thanks!

2021-09-06 12:26 UTC, kpet commented on test_conformance/integer_ops/test_integer_dot_product.cpp
> +    // Check that acceleration properties can be queried
Yes, good catch. Now checking the version.

2021-09-09 05:08 UTC, bashbaug approved these changes
Thanks!

2021-09-21 16:13 UTC, Jeremy-Kemp approved these changes
LGTM

2021-09-29 11:38 UTC, merged