Fix build issue of 32 bitness binaries in vulcan test when using Intel compiler.
KhronosGroup/OpenCL-CTS pull request #1465
Opened 2022-08-10 15:58 UTC by gwawiork

This fix solves error messages:

>C:\Repos\_CTS_KHR\OpenCL-CTS\test_conformance\vulkan\test_vulkan_interop_buffer.cpp(787,44): : error : use of overloaded operator '[]' is ambiguous (with operand types 'VulkanBufferList' and 'int')
2>                    (uint32_t)(vkBufferList[0].getSize());
2>                               ~~~~~~~~~~~~^~
2>C:\Repos\_CTS_KHR\OpenCL-CTS\test_conformance\vulkan\.\vulkan_interop_common/vulkan_list_map.hpp(39,28): note: candidate function
2>    virtual VulkanWrapper &operator[](size_t idx);
2>                           ^
2>C:\Repos\_CTS_KHR\OpenCL-CTS\test_conformance\vulkan\.\vulkan_interop_common/vulkan_list_map.hpp(38,34): note: candidate function
2>    virtual const VulkanWrapper &operator[](size_t idx) const;
C:\Repos\_CTS_KHR\OpenCL-CTS\test_conformance\vulkan\test_vulkan_interop_buffer.cpp(787,44): note: built-in candidate operator[](const unsigned long long *, int)
2>                    (uint32_t)(vkBufferList[0].getSize());
2>                                           ^
2>C:\Repos\_CTS_KHR\OpenCL-CTS\test_conformance\vulkan\test_vulkan_interop_buffer.cpp(787,44): note: built-in candidate operator[](const volatile unsigned long long *, int)
2>C:\Repos\_CTS_KHR\OpenCL-CTS\test_conformance\vulkan\test_vulkan_interop_buffer.cpp(828,28): : warning : unused variable 'buffer_size' [-Wunused-variable]
2>                    size_t buffer_size = vkBufferList[bIdx].getSize();
2>                           ^
2>C:\Repos\_CTS_KHR\OpenCL-CTS\test_conformance\vulkan\test_vulkan_interop_buffer.cpp(1129,44): : error : use of overloaded operator '[]' is ambiguous (with operand types 'VulkanBufferList' and 'int')
2>                    (uint32_t)(vkBufferList[0].getSize());
2>                               ~~~~~~~~~~~~^~
2>C:\Repos\_CTS_KHR\OpenCL-CTS\test_conformance\vulkan\.\vulkan_interop_common/vulkan_list_map.hpp(39,28): note: candidate function
2>    virtual VulkanWrapper &operator[](size_t idx);
2>                           ^
2>C:\Repos\_CTS_KHR\OpenCL-CTS\test_conformance\vulkan\.\vulkan_interop_common/vulkan_list_map.hpp(38,34): note: candidate function
2>    virtual const VulkanWrapper &operator[](size_t idx) const;
2>                                 ^
2>C:\Repos\_CTS_KHR\OpenCL-CTS\test_conformance\vulkan\test_vulkan_interop_buffer.cpp(1129,44): note: built-in candidate operator[](const unsigned long long *, int)
2>                    (uint32_t)(vkBufferList[0].getSize());
2>                                           ^
2>C:\Repos\_CTS_KHR\OpenCL-CTS\test_conformance\vulkan\test_vulkan_interop_buffer.cpp(1129,44): note: built-in candidate operator[](const volatile unsigned long long *, int)
2>C:\Repos\_CTS_KHR\OpenCL-CTS\test_conformance\vulkan\test_vulkan_interop_buffer.cpp(1177,28): : warning : unused variable 'buffer_size' [-Wunused-variable]
2>                    size_t buffer_size = vkBufferList[bIdx].getSize();
2>                           ^

2022-09-02 00:47 UTC, bashbaug commented
FWIW, I get a similar error compiling 32-bit binaries with Visual Studio also (tested VS2019), so this isn't Intel compiler-specific.

I spent a while trying to figure out what was going on here since it was bugging me.  In summary, there are three (really probably only two) relevant overloads in the VulkanList class:

```c++
    virtual const VulkanWrapper &operator[](size_t idx) const;
    virtual VulkanWrapper &operator[](size_t idx);
    virtual operator const VulkanNative *() const;
```

When we index an object that is a VulkanList with the index 0, e.g. `memoryTypeList[0]`, the compiler need to figure out which of these overloads to call.  As I understand, in the 64-bit case, the promotion to size_t is preferred over the implicit conversion to a pointer, so the relevant operator[] gets called.  In the 32-bit case though, there is either a conversion from the signed 32-bit integer 0 to an unsigned 32-bit size_t, or the implicit conversion to a pointer, and the compiler doesn't know how to pick, hence the error.

While the casts to size_t "solve" this problem, it seems error-prone, and I wonder if we can do better.  Can we:

1. Provide a signed integer operator[] in addition to the size_t operator[]?
3. Change the type of operator[] from size_t to integer (probably good enough for our tests)?
2. Provide a templated operator[]?
3. Change from an implicit conversion to a pointer to an explicit conversion to a pointer, say via `virtual const VulkanNative *operator ()() const`?  This requires a little more typing (two characters), but makes it a bit clearer what is going on.

@nikhiljnv any preference?

2022-09-06 22:43 UTC, bashbaug commented
Here's a PR that does (4) and changes from an explicit conversion to a pointer to an explicit conversion.

@nikhiljnv let me know what you think.

@gwawiork can you confirm this fixes your issue and works with the Intel compiler also?  This worked for me, for 32-bit Visual Studio 2019.

2022-09-08 12:00 UTC, gwawiork commented
> nd changes from an explicit conversion to a pointer to an explicit conversion.

Hi @bashbaug I've checked your proposal and it works. I see some (not sure if they are caused  by your change) warnings:
` 3>C:\Repos\_CTS_KHR_32bit\OpenCL-CTS\test_conformance\vulkan\vulkan_interop_common\vulkan_list_map.hpp(333): warning #1011: missing return statement at end of non-void function "VulkanList<VulkanWrapper, VulkanNative>::operator[](size_t={unsigned int}) const [with VulkanWrapper=VulkanSemaphore, VulkanNative=VkSemaphore={uint64_t={unsigned __int64}}]"
3>  }
3>  ^
3>          detected during instantiation of "const VulkanWrapper &VulkanList<VulkanWrapper, VulkanNative>::operator[](size_t={unsigned int}) const [with VulkanWrapper=VulkanSemaphore, VulkanNative=VkSemaphore={uint64_t={unsigned __int64}}]"
3>
3>C:\Repos\_CTS_KHR_32bit\OpenCL-CTS\test_conformance\vulkan\vulkan_interop_common\vulkan_list_map.hpp(343): warning #1011: missing return statement at end of non-void function "VulkanList<VulkanWrapper, VulkanNative>::operator[](size_t={unsigned int}) [with VulkanWrapper=VulkanSemaphore, VulkanNative=VkSemaphore={uint64_t={unsigned __int64}}]"
3>  }
3>  ^
3>          detected during instantiation of "VulkanWrapper &VulkanList<VulkanWrapper, VulkanNative>::operator[](size_t={unsigned int}) [with VulkanWrapper=VulkanSemaphore, VulkanNative=VkSemaphore={uint64_t={unsigned __int64}}]" `

2022-09-22 16:18 UTC, bashbaug commented
> I've checked your proposal and it works. I see some (not sure if they are caused by your change) warnings ...

These are separate warnings that should be fixed.  I see them in 64-bit compiles also.  Example:

```c++
template <class VulkanWrapper, class VulkanNative>
VulkanWrapper &VulkanList<VulkanWrapper, VulkanNative>::operator[](size_t idx)
{
    if (idx < m_wrapperList.size())
    {
        // CHECK_LT(idx, m_wrapperList.size());
        return m_wrapperList[idx].get();
    }
    // **** Note: no return here! ****
}
```

> Looks ok to me.

Cool, if we can get a review approval on https://github.com/KhronosGroup/OpenCL-CTS/pull/1488 we can merge it and 32-bit builds will be working again.  Thanks!

2022-09-26 13:14 UTC, nikhiljnv approved these changes

2022-09-26 14:22 UTC, bashbaug requested changes
Checking: I think we wanted to merge #1488, not this PR?  Leaving a review comment so this doesn't get merged accidentally.

2022-09-26 14:29 UTC, nikhiljnv commented
My bad. I have approved #1488

2022-09-26 14:32 UTC, nikhiljnv commented
> > I've checked your proposal and it works. I see some (not sure if they are caused by your change) warnings ...
> 
> These are separate warnings that should be fixed. I see them in 64-bit compiles also. Example:
> 
> ```c++
> template <class VulkanWrapper, class VulkanNative>
> VulkanWrapper &VulkanList<VulkanWrapper, VulkanNative>::operator[](size_t idx)
> {
>     if (idx < m_wrapperList.size())
>     {
>         // CHECK_LT(idx, m_wrapperList.size());
>         return m_wrapperList[idx].get();
>     }
>     // **** Note: no return here! ****
> }
> ```
> 
> > Looks ok to me.
> 
> Cool, if we can get a review approval on #1488 we can merge it and 32-bit builds will be working again. Thanks!

The warnings above are currently worked-around in #1482 to bypass build failure, but will need to be fixed cleanly

2022-09-28 15:11 UTC, closed without merging