Added cl_khr_fp16 extension support for test_vec_type_hint from basic
KhronosGroup/OpenCL-CTS pull request #1724
Opened 2023-05-12 10:46 UTC by shajder

According to issue description (basic section):

https://github.com/KhronosGroup/OpenCL-CTS/issues/142

2023-05-12 15:09 UTC, svenvh requested changes

2023-05-12 15:09 UTC, svenvh commented on test_conformance/basic/test_vec_type_hint.cpp
> +                                              (const char **)&program_source,
This cast is not valid anymore.

2023-05-15 07:18 UTC, shajder commented on test_conformance/basic/test_vec_type_hint.cpp
> +                                              (const char **)&program_source,
Done

2023-05-15 09:58 UTC, svenvh approved these changes

2023-05-15 11:24 UTC, EwanC approved these changes

2023-06-05 22:40 UTC, lakshmih approved these changes

2023-06-13 06:39 UTC, bashbaug commented
This has three approvals, merging.

2023-06-13 06:39 UTC, merged