add  cl_khr_expect_assume to test_compiler_defines_for_extensions
KhronosGroup/OpenCL-CTS pull request #1735
Opened 2023-05-19 16:51 UTC by norablackcat

2023-05-19 16:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/OpenCL-CTS?pullRequest=1735) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/OpenCL-CTS?pullRequest=1735) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/OpenCL-CTS?pullRequest=1735) it.</sub>

2023-05-23 09:07 UTC, svenvh requested changes

2023-05-23 09:07 UTC, svenvh commented on test_conformance/compiler/test_compiler_defines_for_extensions.cpp
> +    "cl_khr_expect_assume",
As this isn't an API-only extension, I believe this should go right before `cl_khr_subgroup_rotate`. See also the comments on lines 23 and 56.

Please also update `first_API_extension` accordingly.

2023-05-24 07:54 UTC, svenvh submitted a review, later dismissed
LGTM, thanks!

2023-06-05 17:52 UTC, lakshmih approved these changes

2023-06-13 03:55 UTC, bashbaug approved these changes
Thank you!

2023-06-13 04:02 UTC, bashbaug reviewed
Actually, I'm sorry, I did have one question/comment: because this extension does not extend OpenCL C, is it really correct to consider it to be a non-API-only extension?

As-written, this test will fail if an implementation reports support for `cl_khr_expect_assume` but the proper support is NOT "defined in the OpenLC C kernel environment", which does not quite seem correct.

2023-06-13 10:41 UTC, norablackcat commented
I actually had it as an api only extension at first because the extension spec doesn't define any feature macros for it. It does seem a bit silly to me to define cl_khr_expect_assume macro that doesn't do anything because spirv does the work. at least in the rusticl implementation.

2023-06-13 10:48 UTC, karolherbst commented
There are a handful of SPIR-V only extensions now and I suspect we might want to figure how to treat those.

"API only" here basically means, that the online compiler of the OpenCL runtime doesn't expose any feature macro and I think that term is therefore misleading.

So if an extension doesn't define anything on the OpenCL C level, we should just treat them as "API only". Some extensions might define a feature macro in additions to new OpenCL C features and we'll have to check those explicitly anyway.

2023-06-13 10:54 UTC, karolherbst commented
Side note: I don't think we should allow SPIR-V only extensions under `khr`, because they just fragment how compilers actually implement those extensions in their OpenCL C frontend and we might end up with implementations doing it differently. We should rather just define this alongside the SPIR-V side so it's all consistent across various OpenCL C to SPIR-V compilers, which in almost every case will be clang anyway)

2023-06-14 04:59 UTC, bashbaug commented
> If I had a say in it I would say it's api only.

Yeah, I think I agree with this too, though I'm starting to put "api only" in quotes.

I think what really happened here is that we used to only have two categories of extensions: "API-only" extensions, which only affected OpenCL runtime APIs, and "non-API-only" extensions, which affected the (OpenCL C) compiler.  The first category did not need any macros, because they only affected runtime APIs, but the second did.  This is how the two categories of extensions are used in this test.

We've since added a third category of extensions that affect the compiler, but does not affect the OpenCL C compilers, and hence does not need or include a macro.  These aren't really "API-only" extensions, but this categorization works for the purposes of this test.

> Side note: I don't think we should allow SPIR-V only extensions under khr, because they just fragment how compilers actually implement those extensions in their OpenCL C frontend and we might end up with implementations doing it differently. We should rather just define this alongside the SPIR-V side so it's all consistent across various OpenCL C to SPIR-V compilers, which in almost every case will be clang anyway

Can you say a little more about how this might work?  I'd love to have a way to streamline SPIR-V-only extensions but I haven't thought of a clever way to do this just yet.

Note that some of these SPIR-V-only extensions may not have any representation in OpenCL C (`cl_khr_spirv_linkonce_odr` is a good example), but they're still useful so kernels written in other source languages may executed via an OpenCL runtime.

We should probably move this conversation to a separate issue so it doesn't disappear when this PR gets merged.

2023-06-14 10:00 UTC, karolherbst commented
@bashbaug https://github.com/KhronosGroup/OpenCL-Docs/issues/941

2023-06-17 20:55 UTC, karolherbst commented
btw, we already treat `cl_khr_spirv_no_integer_wrap_decoration` as API only, which is also spirv only in its current form.

2023-06-22 04:52 UTC, bashbaug requested changes
Just so this doesn't get merged by accident: we should be considering this an "API-only" extension because it does not formally affect OpenCL C, even though it is really primarily a SPIR-V extension.  See discussion above.

2023-07-18 12:49 UTC, svenvh approved these changes
@bashbaug the latest version treats this as an API-only extension again.  I suppose we can merge it now or do you have any further concerns?

2023-07-18 14:44 UTC, bashbaug approved these changes

2023-07-18 14:44 UTC, bashbaug commented
All good from my end, thanks for the nudge!

2023-07-18 23:07 UTC, bashbaug commented
This has two approvals now, plus @lakshmih's prior approval.  Merging.

2023-07-18 23:07 UTC, merged