Replace OBSOLETE_FORAMT with OBSOLETE_FORMAT
KhronosGroup/OpenCL-CTS pull request #1776
Opened 2023-06-24 07:16 UTC by niranjanjoshi121

In imageHelpers.cpp and few other places in image tests, OBSOLETE_FORMAT is misspelled as OBSOLETE_FORAMT. Fix misspelling by replcaing it with OBSOLETE_FORMAT.

Fixes #1769

2023-06-27 15:13 UTC, svenvh submitted a review, later dismissed

2023-08-03 08:52 UTC, kpet requested changes
If we change the ifdef this will break the code for whomever might have been using this. We don't have definitions for those formats in the standard headers so this can only build with custom headers. I don't think this is code we should have at all in the CTS, certainly not without knowing who's doing what with it. I suggest we just remove any and all code guarded by `OBSOLETE_FORAMT` instead.

2023-09-26 03:33 UTC, bashbaug approved these changes

2023-12-28 18:51 UTC, kpet approved these changes

2023-12-28 18:52 UTC, merged