vulkan test coverage for 1d, 3d, 3dlist images
KhronosGroup/OpenCL-CTS pull request #1883
Opened 2024-01-25 04:56 UTC by pkaur19

2024-01-25 04:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/OpenCL-CTS?pullRequest=1883) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/OpenCL-CTS?pullRequest=1883) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/OpenCL-CTS?pullRequest=1883) it.</sub>

2024-01-27 10:10 UTC, shajder commented
@pkaur19 thanks for this contribution. I am not talkin in behalf of `OpenCL` work group but as someone who recently went across missing coverage of `vulkan` interoperability. As result I've created [this](https://github.com/KhronosGroup/OpenCL-CTS/issues/1834) issue. That being said, I am not sure if `OpenCL-CTS` needs to test list of 3D images (`VulkanImage3DList` class), it sounds to me a bit like time consuming operation meanwhile many vendors already complain about CTS execution time. Would that make any sense to replace list of `image3d_t` test with `image1d_array_t` / `image_2d_array_t` tests ? 

BTW. I went briefly through your code and I can't spot any location of construction of `VulkanImage3DList` object, am I missing something? Is this work in progress?

Please sign CLA license to move forward with your PR, thanks.

2024-01-27 12:35 UTC, nikhiljnv commented on test_conformance/common/vulkan_wrapper/vulkan_list_map.cpp
> +    for (size_t i2DIdx = 0; i2DIdx < numImages; i2DIdx++)
@shajder Were you looking for this?

2024-01-27 12:38 UTC, nikhiljnv commented
@shajder 
The purpose of the test is to add the test coverage you requested as part of #1834, not for addition to generic image test coverage. This is the work-in-progress, but I have left a comment to point you to part you are referring to. Also, I would prefer to get some basic functional changes in and follow up with another PR as we keep adding more coverage.

2024-01-28 13:51 UTC, pkaur19 commented
> @pkaur19 thanks for this contribution. I am not talkin in behalf of `OpenCL` work group but as someone who recently went across missing coverage of `vulkan` interoperability. As result I've created [this](https://github.com/KhronosGroup/OpenCL-CTS/issues/1834) issue. That being said, I am not sure if `OpenCL-CTS` needs to test list of 3D images (`VulkanImage3DList` class), it sounds to me a bit like time consuming operation meanwhile many vendors already complain about CTS execution time. Would that make any sense to replace list of `image3d_t` test with `image1d_array_t` / `image_2d_array_t` tests ?
> 
> BTW. I went briefly through your code and I can't spot any location of construction of `VulkanImage3DList` object, am I missing something? Is this work in progress?
> 
> Please sign CLA license to move forward with your PR, thanks.

Sure if 3DList is not needed I will replace 3DList with 1DList. AlsoI see `VulkanImage2DList` is already present we don't need to implement that.

VulkanImage3DList is created [here](https://github.com/KhronosGroup/OpenCL-CTS/pull/1883/commits/3a532ef4983837211ba252a08abfca9f6e5c2efe#diff-fe4c0fb9e87097b3eaed07e7ed7e71b13c19ba358c44a4c424e9e9f5e33e6a11R235).

2024-01-31 19:12 UTC, joshqti commented on test_conformance/common/vulkan_wrapper/vulkan_wrapper.cpp
> -const VulkanDevice &VulkanSemaphore::getDevice() const { return m_device; }
Why delete this?

2024-01-31 19:18 UTC, joshqti requested changes
I think there may be some rebase stuff that snuck in that needs fixing.  I would like to test this, on our platform before it merges.

2024-01-31 19:18 UTC, joshqti commented on test_conformance/common/vulkan_wrapper/vulkan_wrapper.cpp
> -    {
Why delete this code

2024-01-31 21:09 UTC, joshqti commented
I cannot build this change.  Can you please ensure is builds with CI?

2024-02-06 13:36 UTC, nikhiljnv commented
Closing this in favor of https://github.com/KhronosGroup/OpenCL-CTS/pull/1887. Please, review https://github.com/KhronosGroup/OpenCL-CTS/pull/1887 instead.

2024-02-06 13:36 UTC, closed without merging