Extended printf test with new strings cases
KhronosGroup/OpenCL-CTS pull request #1951
Opened 2024-04-19 12:13 UTC by shajder

Following workplan from issue #1058

Corrections to general test:
-removed duplication of separate tests for each element of `PrintfTestType` vector, instead doTest would iterate over vector related to specific `PrintfTestType` automaticaly
-fixed procedure to assemble kernel source so it can accept only one parameter of the function ( eg. `printf("%%");` )
-incorporated important modifications from #1940 to avoid major conflicts
-warnings, minor corrections
-clang format

Extension for string testing:
-special symbols
-nested symbols
-all ascii characters 
-added new type of test `TYPE_FORMAT_STRING` to verify format string only (according to request from the issue)

2024-05-14 03:49 UTC, lakshmih commented
Reviewing

2024-05-14 13:12 UTC, svenvh requested changes

2024-05-16 19:54 UTC, shajder commented on test_conformance/printf/util_printf.cpp
> +    { { " !\\\"#$%&\'()*+,-./"
done

2024-05-16 19:54 UTC, shajder commented on test_conformance/printf/test_printf.cpp
> +        sourceGen << ");}\n";
done

2024-05-16 19:54 UTC, shajder commented on test_conformance/printf/test_printf.cpp
> +        log_error("Failed to read analysis buffer\n");
done

2024-05-16 19:54 UTC, shajder commented on test_conformance/printf/test_printf.cpp
> +};
done

2024-05-16 19:54 UTC, shajder commented on test_conformance/printf/test_printf.cpp
> +    if (msg) log_error(msg, args...);
done

2024-05-16 19:56 UTC, shajder commented on test_conformance/printf/test_printf.h
> +    std::vector<std::string> genericFormats;
Done, it was moved from previous PR to avoid conflicts but I can solve that afterwards.

2024-05-16 19:56 UTC, shajder commented on test_conformance/printf/util_printf.cpp
corrected

2024-05-20 11:39 UTC, svenvh approved these changes

2024-06-14 16:27 UTC, svenvh approved these changes

2024-06-17 17:38 UTC, lakshmih approved these changes

2024-06-18 15:44 UTC, merged