cl_fill_image: Use CL_DEVICE_VERSION instead of CL_DEVICE_NUMERIC_VER…
KhronosGroup/OpenCL-CTS pull request #2043
Opened 2024-08-09 04:41 UTC by lakshmih

…SION

CL_DEVICE_NUMERIC_VERSION is only available from OpenCL 3.0 Use CL_DEVICE_VERSION instead.

2024-08-09 10:26 UTC, kpet requested changes
I suggest you use `get_device_cl_version` from the harness instead.

2024-08-13 07:45 UTC, kpet commented on test_conformance/images/clFillImage/test_fill_generic.cpp
> +                    int major = (version.to_int()) / 10;
We should probably add `Version::major()` and `Version::minor()` getters to the harness code so users don't have to do math.

2024-09-24 16:05 UTC, bashbaug submitted a review, later dismissed

2024-12-02 18:54 UTC, kpet submitted a review, later dismissed
The change looks good but it seems you need to rebase or merge `main`.

2024-12-03 16:55 UTC, bashbaug approved these changes
Merging as discussed in the December 3rd teleconference.

2024-12-03 16:55 UTC, merged