add tests for cl_ext_buffer_device_address
KhronosGroup/OpenCL-CTS pull request #2192
Opened 2024-12-14 20:57 UTC by franz

2024-12-16 17:30 UTC, bashbaug reviewed
Could you use the new test registration framework for these tests?  It should reduce a bit of the test boilerplate, and then we won't need to switch them over later.

https://github.com/KhronosGroup/OpenCL-CTS/pull/2151

2024-12-19 15:01 UTC, franz commented
@bashbaug  added, based on the device_timer test.

2025-01-15 09:16 UTC, pjaaskel requested changes

2025-01-15 09:16 UTC, pjaaskel commented on test_conformance/extensions/cl_ext_buffer_device_address/buffer_device_address.cpp
> +        dev_addr_buffer = clCreateBuffer(
Please update to 1.0.0 which uses clCreateBufferWithProperties()

2025-01-15 09:16 UTC, pjaaskel commented on test_conformance/extensions/cl_ext_buffer_device_address/buffer_device_address.cpp
> +            error = clEnqueueWriteBuffer(queue, buffer_in_long,
Indent.

2025-01-17 19:49 UTC, franz commented on test_conformance/extensions/cl_ext_buffer_device_address/buffer_device_address.cpp
> +
added

2025-01-20 08:38 UTC, karolherbst commented
Not sure if you got to it yet, but I've fixed the test so it compiles and conforms to the recent version, might need some cleanup and reformatting and all that:

```patch
@@ -59,8 +59,10 @@ public:
     bool Skip()
     {
         cl_int error = 0;
-        clMemWrapper TempBuffer = clCreateBuffer(
-            context, (cl_mem_flags)(CL_MEM_READ_WRITE | address_type),
+
+        cl_mem_properties buf_props[] = { address_type, CL_TRUE, 0 };
+        clMemWrapper TempBuffer = clCreateBufferWithProperties(
+            context, buf_props, CL_MEM_READ_WRITE,
             (size_t)BUF_SIZE * sizeof(cl_int), nullptr, &error);
         return (error != CL_SUCCESS);
     }
@@ -108,7 +110,7 @@ public:
 
         // Test a buffer which doesn't have any hostptr associated with it.
         dev_addr_no_host_buffer =
-            clCreateBuffer(context, CL_MEM_READ_WRITE | address_type,
+            clCreateBufferWithProperties(context, buf_props, CL_MEM_READ_WRITE,
                            sizeof(cl_int) * BUF_SIZE, nullptr, &error);
         test_error(error, "clCreateBuffer with device address 2 failed\n");
 
@@ -189,7 +191,7 @@ private:
             sizeof(cl_int) * BUF_SIZE, svm_buffer(), &error);
         test_error(error, "clCreateBuffer with device address 1 failed\n");
 
-        cl_mem_device_address_EXT Addr = 0;
+        cl_mem_device_address_ext Addr = 0;
         error = clGetMemObjectInfo(buffer, CL_MEM_DEVICE_ADDRESS_EXT,
                                    sizeof(Addr), &Addr, NULL);
         test_error(error,
@@ -376,10 +378,11 @@ private:
             check_device_address_from_api(dev_addr_buffer, DeviceAddrFromAPI);
         test_error_fail(error, "dev_addr_buffer does not have device address")
 
+        cl_mem_device_address_ext DeviceAddrFromAPIP2 = (cl_mem_device_address_ext)(((cl_uint *)DeviceAddrFromAPI) + 2);
             error = clSetKernelArgDevicePointer(
                 ptr_arith_kernel, 0,
-                (cl_mem_device_address_ext)(((cl_uint *)DeviceAddrFromAPI)
-                                            + 2));
+                &DeviceAddrFromAPIP2);
+
         test_error_fail(error, "clSetKernelArgDevicePointer failed\n");
         error = clSetKernelArg(ptr_arith_kernel, 1, sizeof(cl_mem),
                                &buffer_out_int);
```

2025-01-20 10:02 UTC, franz commented
@karolherbst  thanks, added

2025-01-20 14:31 UTC, karolherbst commented
I forgot to bump the version

```patch
diff --git a/test_conformance/extensions/cl_ext_buffer_device_address/main.cpp b/test_conformance/extensions/cl_ext_buffer_device_address/main.cpp
index 1ce30008..d8475647 100644
--- a/test_conformance/extensions/cl_ext_buffer_device_address/main.cpp
+++ b/test_conformance/extensions/cl_ext_buffer_device_address/main.cpp
@@ -38,7 +38,7 @@ test_status InitCL(cl_device_id device)
 
     cl_version ext_version =
         get_extension_version(device, "cl_ext_buffer_device_address");
-    if (ext_version != CL_MAKE_VERSION(0, 9, 1))
+    if (ext_version != CL_MAKE_VERSION(1, 0, 0))
     {
         log_info("The test is written against cl_ext_buffer_device_address "
                  "extension version 0.9.1, device supports version: %u.%u.%u\n",
```

2025-02-11 16:20 UTC, bashbaug commented
Note, we are going to need to merge the header changes for cl_ext_buffer_device_address before this PR, or figure out some other way to avoid breaking the build.  https://github.com/KhronosGroup/OpenCL-Headers/pull/273

2025-02-26 17:54 UTC, bashbaug commented
Since we merged the header changes, the CI builds should finish now.  @franz could you please push a dummy commit or otherwise cause the tests to rerun to verify?

It'd be nice to have an approval from @pjaaskel or @karolherbst before merging.

2025-02-27 12:23 UTC, pjaaskel approved these changes
LGTM after the tests pass.

2025-02-27 13:16 UTC, karolherbst commented
needs this patch to compile against upstream headers:

```patch
diff --git a/test_conformance/extensions/cl_ext_buffer_device_address/buffer_device_address.cpp b/test_conformance/extensions/cl_ext_buffer_device_address/buffer_device_address.cpp
index d91e3e6d..7fe4522b 100644
--- a/test_conformance/extensions/cl_ext_buffer_device_address/buffer_device_address.cpp
+++ b/test_conformance/extensions/cl_ext_buffer_device_address/buffer_device_address.cpp
@@ -140,7 +140,7 @@ private:
     cl_mem_properties address_type;
 
     int check_device_address_from_api(cl_mem buf,
-                                      cl_mem_device_address_EXT &Addr)
+                                      cl_mem_device_address_ext &Addr)
     {
         Addr = 0;
         cl_int error = clGetMemObjectInfo(buf, CL_MEM_DEVICE_ADDRESS_EXT,
@@ -213,7 +213,7 @@ private:
     {
         cl_int error = 0;
         cl_ulong DeviceAddrFromKernel = 0;
-        cl_mem_device_address_EXT DeviceAddrFromAPI = 0;
+        cl_mem_device_address_ext DeviceAddrFromAPI = 0;
 
         for (int i = 0; i < BUF_SIZE; ++i)
         {
@@ -281,7 +281,7 @@ private:
                              clKernelWrapper &ind_access_kernel)
     {
         cl_int error = 0;
-        cl_mem_device_address_EXT DeviceAddrFromAPI = 0;
+        cl_mem_device_address_ext DeviceAddrFromAPI = 0;
 
         int DataIn = 0x12348765;
         int DataOut = -1;
@@ -355,7 +355,7 @@ private:
                             clKernelWrapper &ptr_arith_kernel)
     {
         cl_int error = 0;
-        cl_mem_device_address_EXT DeviceAddrFromAPI = 0;
+        cl_mem_device_address_ext DeviceAddrFromAPI = 0;
         int DataOut = -1;
         int DataIn = 0x12348765;
 
```

2025-02-27 13:46 UTC, karolherbst commented on test_conformance/extensions/cl_ext_buffer_device_address/main.cpp
> +    if (ext_version != CL_MAKE_VERSION(1, 0, 0))
`1, 0, 2`

2025-02-27 14:11 UTC, franz commented on test_conformance/extensions/cl_ext_buffer_device_address/main.cpp
> +    if (ext_version != CL_MAKE_VERSION(1, 0, 0))
@karolherbst  thanks. I'll add this and rebase on main branch

2025-02-27 14:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/OpenCL-CTS?pullRequest=2192) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/OpenCL-CTS?pullRequest=2192) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/OpenCL-CTS?pullRequest=2192) it.</sub>

2025-03-18 16:10 UTC, bashbaug commented
@karolherbst do these tests look OK to you?  Thanks!

2025-03-18 17:58 UTC, karolherbst commented
Should be squashed and `check_svm_buffer` needs to be called somewhere, but besides that I think it's ready to go. At least on my bda + SVM branch it passes for me (after a little fix I needed for `check_svm_buffer`).

2025-03-18 20:14 UTC, bashbaug commented
We'll squash and merge by default, so that won't be a problem.

@franz can you please figure out where `check_svm_buffer` should be called?

2025-03-19 18:55 UTC, karolherbst approved these changes
looks good, thanks!

2025-03-19 21:08 UTC, bashbaug approved these changes
Great, I'm going to go ahead and merge this then.  We can always make additional improvements in subsequent PRs.  Thanks!

2025-03-19 21:08 UTC, merged